server:
  port: 8083

spring:
  application:
    name: inventory-service
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    tags:
      application: ${spring.application.name:inventory-service}
