# JPA + Hibernate
spring:

  # PostgresSQL
  datasource:
    url: jdbc:postgresql://localhost:5433/orders
    username: orders
    password: orders

    hikari:
      pool-name: OrdersHikariPool
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 5000
      leak-detection-threshold: 20000

  # JPA
  jpa:
    hibernate:
      ddl-auto: validate
      format_sql: false
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: false

  # Flyway
  flyway:
    enabled: true
    clean-disabled: true
    locations: classpath:db/migration

  # Kafka
  kafka:
    bootstrap-servers: localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: order-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "pl.xsware.orders.application"
        spring.json.use.type.headers: true
    listener:
      ack-mode: record


# Scheduler
orders:
  outbox:
    dispatcher:
      enabled: true
      fixed-delay: PT15S
      initial-delay: PT10S
    claim-mode: SKIP_LOCKED  # or ADVISORY

# Metrics
management:
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  metrics:
    export:
      otlp:
        enabled: false

# Custom properties
app:
  kafka:
    topics:
      payment-requested: payments.payment-requested.v1
      payment-succeeded: payments.payment-succeeded.v1
      payment-failed: payments.payment-failed.v1
      payment-cancelled: payments.payment-cancelled.v1
