# Start core
#docker compose -f infrastructure/postgres/docker-compose.yml up -d
#docker compose -f infrastructure/redis/docker-compose.yml up -d
#docker compose -f infrastructure/kafka/docker-compose.yml up -d

# Migracje
#docker compose -f infrastructure/flyway/docker-compose.yml run --rm flyway-orders
#docker compose -f infrastructure/flyway/docker-compose.yml run --rm flyway-payments
#docker compose -f infrastructure/flyway/docker-compose.yml run --rm flyway-inventory
#docker compose -f infrastructure/flyway/docker-compose.yml run --rm flyway-notifications

# ELK
#docker compose -f infrastructure/observability/elastic/docker-compose.yml up -d

# Run network
#docker network create platform-net

